version: '3.8'

services:
  frontend:
    build:
      context: ./ai_enhanced_resume_builder/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

  backend:
    build:
      context: ./ai_enhanced_resume_builder/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
